### ISSUE TITLE
가상환경 사용방법

### ISSUE THREAD

**Issue by wonkyoc** [jafffy/linux_usage_wiki#1]
__To do__
* [x] Virtualbox
* [x] VMware(Optional)
    
__VMware 사용이유__
* Windows 에선 무료이고 Virtualbox 보다 더 좋은 성능을 보입니다.
* 많은 Lenovo 모델들이 Virtualbox 를 제대로 구동하지 못 합니다.

**Comment by jafffy** [comment]
I think so 👍
